apiVersion: v1
kind: Pod
metadata:
  name: shell
  labels:
    app: shell
spec:
  containers:
    - name: shell
      image: amazon/aws-cli
      command: ["tail", "-f", "/dev/stdout"]
      resources:
        limits:
          cpu: 250m
          memory: 250M
